(module
 (type $i32_i32_i32_=>_none (func_subtype (param i32 i32 i32) func))
 (type $i32_i32_=>_i32 (func_subtype (param i32 i32) (result i32) func))
 (import "env" "_g" (func $~lib/builtins/_g (param i32 i32) (result i32)))
 (global $resolve-nested/Outer.Inner.a (mut i32) (i32.const 0))
 (global $resolve-nested/Outer.Inner.b (mut i32) (i32.const 0))
 (global $resolve-nested/Outer.Inner.c (mut i32) (i32.const 0))
 (global $resolve-nested/Outer.Inner.d (mut i32) (i32.const 0))
 (global $resolve-nested/Outer.Inner.e (mut i32) (i32.const 0))
 (global $resolve-nested/Outer.Inner.f (mut i32) (i32.const 0))
 (global $resolve-nested/Outer.a (mut i32) (i32.const 0))
 (global $resolve-nested/Outer.b (mut i32) (i32.const 0))
 (global $resolve-nested/Outer.c (mut i32) (i32.const 0))
 (global $resolve-nested/Outer.d (mut i32) (i32.const 0))
 (global $resolve-nested/Outer.e (mut i32) (i32.const 0))
 (global $resolve-nested/a (mut i32) (i32.const 0))
 (global $resolve-nested/b (mut i32) (i32.const 0))
 (global $resolve-nested/c (mut i32) (i32.const 0))
 (memory $0 1)
 (table $0 1 1 funcref)
 (elem $0 (i32.const 1))
 (export "outer" (func $resolve-nested/outer))
 (export "memory" (memory $0))
 (func $resolve-nested/outer (type $i32_i32_i32_=>_none) (param $a i32) (param $b i32) (param $c i32)
  nop
 )
)
