name: Release semantic version

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

jobs:
  release-semantic-version:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Set release version environment variable
      run: |
        # If the workflow was triggered by a workflow_dispatch event, use the version input
        # Else, get the release version from the tag
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          RELEASE_VERSION=${{ github.event.inputs.version }}
        else
          RELEASE_VERSION=${GITHUB_REF#refs/tags/v}
        fi
        echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
        npm version $RELEASE_VERSION --no-git-tag-version --allow-same-version
        echo "Publishing release: $RELEASE_VERSION"
    - name: Publish packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm publish --access public
